version: '3'

services:
  react_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "6969:6969"